### PR TITLE
Assignment 1A +++ Assignment 2C

### PR DESCRIPTION
**Pull request by gpujada**
modified for assignment 1a

### CODE REVIEW

**Comment by gpujada** [comment]
i guess GitHub wouldn't let me make another separate pull request? added assignment 2c

**Comment by gpujada** [comment]
just finished reading the end of the instructions. of course there's no new pull request haha

**Comment by cengique** [comment]
Good

**Comment by cengique** [comment]
Right, everything shows in here, no need for new PR.

**Pull request closed without merging**
